[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "vite"
  targetPort = 5173
  functionsPort = 9999

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

